services:
  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./products.csv:/data/products.csv
      - ./init-cache.sh:/docker-entrypoint-initdb.d/init-cache.sh
    entrypoint: ["/bin/sh", "-c","redis-server --daemonize yes && sleep 5 && /docker-entrypoint-initdb.d/init-cache.sh && tail -f /dev/null"]